# Word2Vec

In [3]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from gensim.models import Word2Vec

C:\Users\arun\Anaconda3\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [24]:
preprocessed_reviews = ['baking soda works great cooking health reasons take acid indigestion heart burn tsp half glass water gone use make body alkaline great changing ph level body',
 'got girlfriend birthday fruit actually tasted fresh yummy love dark chocolate loved dark chocolate almonds next time give organic version product someone close share',
 'would call summer wine light strong pear notes almost clear color nice finish good wine not really like wine',
 'really worried ordered phantom power would make overheat apparently worried nothing use paired blue yeti pro seriously beefy microphone running shielded cable eighty feet away absolutely great one downside seen piece kit occasionally not register usb device granted seen happen always want double check connections',
 'rarely find potato chips live decided find online satisfy cravings cannot happier ordering amazon chips arrived fast box protected crushing excellent ordering',
 'best gluten free mix tried recipes box vouch pancakes waffles biscuits edible not enjoyable pancakes waffles also freeze well also recommend betty crocker glutenfree recipe collection magazine extra recipes try without mix magazine thus far made chicken dumplings dumplings disintegrate bit easily still good fruit swirl coffee cake used full pie filling per used apple lemon pie fillings thought cake tasted rather like cobbler dry danish pastry mix quick easy tastes good versatile hey although packaging mix little boxes bit pain serve keep mix fresh',
 'not eat many chips love great buy arrived quick packed great expiration date ways away awhile enjoy great natural potato flavor love brown russet hardy flavor fit description tee',
 'even kids like always asking hot cocoa not sweet chocolaty not super high sugar calories great little treat enjoy',
 'bar harbor clam chowder absolutely not usually fan soup really picky clam chowder said get stuff bulk several reasons first great flavor clams potatoes second like fact ingredients natural third one adjust level creaminess viscosity one adds soup like use mixture milk cream fourth plus soup contains neither bacon nor excessive amounts spice pepper two things ruin clam chowder know bacon popular lot folks really want taste clams bowl new england clam chowder like respect think like soup p child fan friendly clam chowder changed recipe bar harbor even better',
 'guess thought usual commercial price not seem bad arrived saw somewhat smaller less half gallon not see size much problem rethink would use recipe free shipping helped feeling better purchase saw size store would not pay oz would see fresh clams would cost first would like made clams bigger chunks could buy fresh add clam chowder made bigger chunks snow makes good product despite price',
 'keep pamela baking mix gallon container spin bucket seal lid pantry want make pancakes waffles start day right take cup two mix add teaspoon vanilla extract egg olive oil ready go enjoy purchasing lb bag easy store keeps fresh months yet accessible consistent performance special treat like add hemp seed top waffles cooking fresh blueberries strawberries topping agave syrup',
 'used use coffee visited costa rica gave aunt thinks best coffee gave christmas excellent',
 'first introduced red rice beans chips hometown bethlehem pa moved north carolina unable find chips local area trips back home would buy bunch bags bring back nc discovered could order line life great chips time favorite everyone serve loves gotta try hooked nancy walsh',
 'wonderful product bread mixes tried amazon not disappointing back make great christmas presents',
 'first found year old go gluten free little worried would handle gf bisquick made lot easier able make favorite foods chicken fingers corn dogs pizza chinese sweet sour chicken mix pancakes also big hit house quick easy recipes box chinese take chicken finger recipe cute pieces chicken bite size pieces bake according recipe cook rice use gf sweet sour sauce quick simple easy meal tastes wonderful',
 'sun chips ok substitute usual potato corn whatever chip cooked oil salted not nearly un palatable thought would added heart healthy diet regime good except amulti grain style texture sheet plywood',
 'fun great price one party favors son birthday party huge hit buy baseball team group outings box like good ol days although remember prizes better back maybe expectations lower since',
 'dog loves food serious gastrointestinal problems not clearing started newman since regular happy healthy',
 'not eaten popcorn tasted part gift daughter grad school likes fluffy quality popped corn not many hulls also big bag makes think make last christmas remains seen without buy good snack poor grad student',
 'spice mix recreate taste favorite restaurant stews potent not use much smells heavenly perfect meat bean stews',
 'instead simple solution lamb rice sent simple lamb oatmeal dog likes next time make sure sent right food not know open put food container',]

In [38]:
listofwords = []
for sentance in preprocessed_reviews:
    listofwords.append(sentance.split())
    
w2vmodel = Word2Vec(listofwords,min_count=5,size=50)
#list of words in word2vec model
w2vwords = list(w2vmodel.wv.vocab)
print(w2vwords)

['great', 'use', 'make', 'fresh', 'would', 'good', 'not', 'like', 'chips', 'mix', 'recipe', 'chicken', 'buy', 'clam', 'chowder']


In [42]:
#words of first review
listofwords[0]

['baking',
 'soda',
 'works',
 'great',
 'cooking',
 'health',
 'reasons',
 'take',
 'acid',
 'indigestion',
 'heart',
 'burn',
 'tsp',
 'half',
 'glass',
 'water',
 'gone',
 'use',
 'make',
 'body',
 'alkaline',
 'great',
 'changing',
 'ph',
 'level',
 'body']

In [39]:
#example: vector of each word created by w2v model
w2vmodel.wv['use']

array([ 0.00288393,  0.0039188 ,  0.00468311, -0.00908116,  0.00479992,
        0.00358471,  0.00112401, -0.00424932,  0.00110552,  0.00969205,
        0.00788773, -0.00882963,  0.00202138,  0.00723123,  0.00528644,
        0.00371784,  0.00416327,  0.00061227, -0.00522876, -0.00295116,
        0.00635336,  0.00146099, -0.00983775, -0.00049973,  0.00199312,
       -0.00663965, -0.00734409,  0.00735446, -0.00873247, -0.00695296,
        0.0068963 , -0.0043568 ,  0.00906399, -0.00712066,  0.00996415,
        0.00796806,  0.0047817 , -0.00553946,  0.00236817,  0.00988753,
       -0.00128688,  0.00503099, -0.00114999, -0.00213074,  0.0006531 ,
        0.00129721, -0.00450396, -0.00217756,  0.00161538,  0.0043157 ],
      dtype=float32)

# Avg- word2vec

In [34]:
#average word2vec
list_of_avgw2v = []  #list of vector for each review
for sentance in listofwords:
    sent_vector = np.zeros(50)
    count = 0
    for word in sentance:
        if word in w2vwords:
            sent_vector += w2vmodel.wv[word] #adding w2vec vector to zero vector
            count += 1
    if count != 0:
        sent_vector /= count #dividing sum of w2vectors with count
    list_of_avgw2v.append(sent_vector)

In [37]:
list_of_avgw2v[1:10]

[array([-1.12782489e-03, -1.33732404e-03,  2.72321724e-03, -1.14197284e-03,
        -7.28782470e-05,  1.66157202e-03,  6.10402878e-03, -8.71056039e-03,
         2.46621924e-03, -4.31072991e-03, -8.02897755e-03,  1.53711601e-03,
         9.30540171e-03,  8.84269737e-03, -4.36173612e-03,  6.82319375e-03,
        -4.66642668e-03, -3.82614345e-03,  6.07121876e-03, -5.15935151e-03,
         5.59466716e-04,  6.96281483e-03,  9.91382170e-03,  8.96636583e-03,
        -4.90086479e-03, -7.04293489e-04, -5.84290363e-03, -1.75583686e-04,
         8.77030008e-03,  1.95129297e-03,  7.89933663e-04, -3.46579892e-03,
        -5.23912604e-04,  3.96382529e-03,  8.12609098e-04,  6.39481656e-03,
         4.40276880e-03, -7.31428619e-04,  6.01215241e-03, -6.26263255e-03,
         2.09219079e-03,  3.07001267e-03, -8.48279800e-03,  4.91593918e-03,
        -8.51797592e-03,  4.04579239e-03,  7.05413613e-03, -6.65177964e-03,
        -5.20102307e-03, -6.88160956e-03]),
 array([-3.01858579e-03, -3.99650606e-04, -4

# Tfidf- word2Vec

In [29]:
tfidf_vector = TfidfVectorizer()
tfidf_vector.fit(preprocessed_reviews)
tfidf_words = tfidf_vector.get_feature_names()
#idf values
idf_values = list(tfidf_vector.idf_)  
#creating a dictionary which relates tfidf words with their idf values
idf_dictionary = dict(zip(tfidf_words,idf_values))

In [32]:
list_of_tfidfw2v = []
for sentance in listofwords:
    sent_vector_t = np.zeros(50)
    tfidf_weight = 0
    for word in sentance:
        if word in w2vwords and word in tfidf_words:
            #tf = no of times a term t appear in the document / total number of terms in the document
            tf = sentance.count(word)/len(sentance)
            #tfidf  = tf * idf
            tfidf_value =  tf * idf_dictionary[word] 
            sent_vector_t += (w2vmodel.wv[word] * tfidf_value)
            tfidf_weight += tfidf_value
        if tfidf_weight != 0:
            sent_vector_t /= tfidf_weight
    list_of_tfidfw2v.append(sent_vector_t)

In [36]:
list_of_tfidfw2v[1:10]

[array([-6.38820713e+13, -7.57484912e+13,  1.54248018e+14, -6.46834390e+13,
        -4.12795766e+12,  9.41144870e+13,  3.45743396e+14, -4.93382128e+14,
         1.39691185e+14, -2.44167660e+14, -4.54776021e+14,  8.70650738e+13,
         5.27075028e+14,  5.00866598e+14, -2.47056745e+14,  3.86478225e+14,
        -2.64314968e+14, -2.16719784e+14,  3.43884970e+14, -2.92235151e+14,
         3.16892222e+13,  3.94386615e+14,  5.61537076e+14,  5.07871411e+14,
        -2.77593964e+14, -3.98924758e+13, -3.30952794e+14, -9.94538236e+12,
         4.96765903e+14,  1.10524812e+14,  4.47432933e+13, -1.96309213e+14,
        -2.96753723e+13,  2.24518344e+14,  4.60276698e+13,  3.62214153e+14,
         2.49380911e+14, -4.14294589e+13,  3.40539361e+14, -3.54727005e+14,
         1.18505528e+14,  1.73891148e+14, -4.80481232e+14,  2.78447832e+14,
        -4.82473802e+14,  2.29161111e+14,  3.99559212e+14, -3.76768993e+14,
        -2.94595491e+14, -3.89787006e+14]),
 array([-1.60960333e+12, -7.40621061e+11, -7